parameters:
#    trinity_app.example.class: Trinity\AppBundle\Example

services:
#    trinity_app.example:
#        class: %trinity_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
