language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script: composer install -n

script: phpunit -c app

notifications:
  email:
    - subv2112@gmail.com
    - hramires01@gmail.com
    - zebini.alves@gmail.com
  irc: "irc.rizon.net#trainingyard"