trinity_client_app:
    resource: "@TrinityClientAppBundle/Controller/"
    type:     annotation
    prefix:   /

trinity_app:
    resource: "@TrinityAppBundle/Resources/config/routing.yml"
    prefix:   /

